# Generated by Django 5.2.12 on 2026-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_remove_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
