# Generated by Django 5.2.12 on 2026-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("kz", "Kazakh")],
                default="en",
                max_length=2,
                verbose_name="Preferred Language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="UTC", max_length=64, verbose_name="Timezone"
            ),
        ),
    ]
