# Generated by Django 5.2.12 on 2026-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_preferred_language_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("kk", "Kazakh")],
                default="en",
                max_length=2,
                verbose_name="Preferred Language",
            ),
        ),
    ]
